// Generated by purs bundle 0.12.5
var PS = {};
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["Control.Semigroupoid"] = $PS["Control.Semigroupoid"] || {};
  var exports = $PS["Control.Semigroupoid"];
  var Semigroupoid = function (compose) {
      this.compose = compose;
  };
  var semigroupoidFn = new Semigroupoid(function (f) {
      return function (g) {
          return function (x) {
              return f(g(x));
          };
      };
  });
  var compose = function (dict) {
      return dict.compose;
  };
  var composeFlipped = function (dictSemigroupoid) {
      return function (f) {
          return function (g) {
              return compose(dictSemigroupoid)(g)(f);
          };
      };
  };
  exports["compose"] = compose;
  exports["Semigroupoid"] = Semigroupoid;
  exports["composeFlipped"] = composeFlipped;
  exports["semigroupoidFn"] = semigroupoidFn;
})(PS);
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["Control.Category"] = $PS["Control.Category"] || {};
  var exports = $PS["Control.Category"];
  var Control_Semigroupoid = $PS["Control.Semigroupoid"];                
  var Category = function (Semigroupoid0, identity) {
      this.Semigroupoid0 = Semigroupoid0;
      this.identity = identity;
  };
  var identity = function (dict) {
      return dict.identity;
  };
  var categoryFn = new Category(function () {
      return Control_Semigroupoid.semigroupoidFn;
  }, function (x) {
      return x;
  });
  exports["Category"] = Category;
  exports["identity"] = identity;
  exports["categoryFn"] = categoryFn;
})(PS);
(function(exports) {
  "use strict";

  exports.showIntImpl = function (n) {
    return n.toString();
  };
})(PS["Data.Show"] = PS["Data.Show"] || {});
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["Data.Show"] = $PS["Data.Show"] || {};
  var exports = $PS["Data.Show"];
  var $foreign = $PS["Data.Show"];
  var Show = function (show) {
      this.show = show;
  };                                                 
  var showInt = new Show($foreign.showIntImpl);
  var show = function (dict) {
      return dict.show;
  };
  exports["Show"] = Show;
  exports["show"] = show;
  exports["showInt"] = showInt;
})(PS);
(function(exports) {
  "use strict";
  var React =require("react");           

  exports.createComponent = (function() {
    // Begin component prototype functions
    // (`this`-dependent, defined outside `createComponent`
    // for a slight performance boost)
    function toSelf() {
      var instance = this;
      var setStateThen = function(update) {
        return function(effects) {
          return function() {
            instance.setState(function(state) {
              return { $$state: update(state.$$state) };
            }, effects);
          };
        };
      };
      var self = {
        props: instance.props.$$props,
        state: instance.state === null ? null : instance.state.$$state,
        setState: function(update) {
          return setStateThen(update)(undefined);
        },
        setStateThen: setStateThen,
        instance_: instance
      };
      return self;
    }

    function componentDidMount() {
      var didMount = this.$$spec.didMount;
      if (didMount !== undefined) {
        didMount(this.toSelf())();
      }
    }

    function shouldComponentUpdate(nextProps, nextState) {
      var shouldUpdate = this.$$spec.shouldUpdate;
      return shouldUpdate === undefined
        ? true
        : shouldUpdate(this.toSelf())({
            nextProps: nextProps.$$props,
            nextState: nextState === null ? null : nextState.$$state
          });
    }

    function componentDidUpdate(prevProps, prevState) {
      var didUpdate = this.$$spec.didUpdate;
      if (didUpdate !== undefined) {
        didUpdate(this.toSelf())({
          prevProps: prevProps.$$props,
          prevState: prevState === null ? null : prevState.$$state
        })();
      }
    }

    function componentWillUnmount() {
      this.$$mounted = false;
      var willUnmount = this.$$spec.willUnmount;
      if (willUnmount !== undefined) {
        willUnmount(this.toSelf())();
      }
    }

    function render() {
      return this.$$spec.render(this.toSelf());
    }
    // End component prototype functions

    return function(displayName) {
      var Component = function constructor(props) {
        this.$$mounted = true;
        this.$$spec = props.$$spec;
        this.state =
          // React may optimize components with no state,
          // so we leave state null if it was left as
          // the default value.
          this.$$spec.initialState === undefined
            ? null
            : { $$state: this.$$spec.initialState };
        return this;
      };

      Component.displayName = displayName;
      Component.prototype = Object.create(React.Component.prototype);
      Component.prototype.constructor = Component;
      Component.prototype.toSelf = toSelf;
      Component.prototype.shouldComponentUpdate = shouldComponentUpdate;
      Component.prototype.componentDidMount = componentDidMount;
      Component.prototype.componentDidUpdate = componentDidUpdate;
      Component.prototype.componentWillUnmount = componentWillUnmount;
      Component.prototype.render = render;

      return Component;
    };
  })();

  exports.make = function(_unionDict) {
    return function($$type) {
      return function($$spec) {
        var $$specPadded = {
          initialState: $$spec.initialState,
          render: $$spec.render,
          didMount: $$spec.didMount,
          shouldUpdate: $$spec.shouldUpdate,
          didUpdate: $$spec.didUpdate,
          willUnmount: $$spec.willUnmount
        };
        return function($$props) {
          var props = {
            $$props: $$props,
            $$spec: $$specPadded
          };
          return React.createElement($$type, props);
        };
      };
    };
  };

  exports.element_ = function(component, props) {
    return React.createElement.apply(
      null,
      [component, props].concat((props && props.children) || null)
    );
  };
})(PS["React.Basic"] = PS["React.Basic"] || {});
(function(exports) {
  "use strict";

  exports.runFn2 = function (fn) {
    return function (a) {
      return function (b) {
        return fn(a, b);
      };
    };
  };
})(PS["Data.Function.Uncurried"] = PS["Data.Function.Uncurried"] || {});
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["Data.Function.Uncurried"] = $PS["Data.Function.Uncurried"] || {};
  var exports = $PS["Data.Function.Uncurried"];
  var $foreign = $PS["Data.Function.Uncurried"];
  exports["runFn2"] = $foreign.runFn2;
})(PS);
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["React.Basic"] = $PS["React.Basic"] || {};
  var exports = $PS["React.Basic"];
  var $foreign = $PS["React.Basic"];
  var Data_Function_Uncurried = $PS["Data.Function.Uncurried"];             
  var element = Data_Function_Uncurried.runFn2($foreign.element_);
  exports["element"] = element;
  exports["createComponent"] = $foreign.createComponent;
  exports["make"] = $foreign.make;
})(PS);
(function(exports) {
  "use strict";

  // module Unsafe.Coerce

  exports.unsafeCoerce = function (x) {
    return x;
  };
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["Unsafe.Coerce"] = $PS["Unsafe.Coerce"] || {};
  var exports = $PS["Unsafe.Coerce"];
  var $foreign = $PS["Unsafe.Coerce"];
  exports["unsafeCoerce"] = $foreign.unsafeCoerce;
})(PS);
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["React.Basic.DOM"] = $PS["React.Basic.DOM"] || {};
  var exports = $PS["React.Basic.DOM"];
  var Unsafe_Coerce = $PS["Unsafe.Coerce"];                                     
  var text = Unsafe_Coerce.unsafeCoerce;
  exports["text"] = text;
})(PS);
(function(exports) {
  "use strict";

  exports.unsafePerformEffect = function (f) {
    return f();
  };
})(PS["Effect.Unsafe"] = PS["Effect.Unsafe"] || {});
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["Effect.Unsafe"] = $PS["Effect.Unsafe"] || {};
  var exports = $PS["Effect.Unsafe"];
  var $foreign = $PS["Effect.Unsafe"];
  exports["unsafePerformEffect"] = $foreign.unsafePerformEffect;
})(PS);
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["React.Basic.Events"] = $PS["React.Basic.Events"] || {};
  var exports = $PS["React.Basic.Events"];
  var Control_Category = $PS["Control.Category"];
  var Control_Semigroupoid = $PS["Control.Semigroupoid"];          
  var EventFn = function (x) {
      return x;
  };
  var unsafeEventFn = EventFn;
  var semigroupoidBuilder = Control_Semigroupoid.semigroupoidFn;
  var handler = function (v) {
      return function (cb) {
          return function ($22) {
              return cb(v($22))();
          };
      };
  };
  var categoryBuilder = Control_Category.categoryFn;
  exports["unsafeEventFn"] = unsafeEventFn;
  exports["handler"] = handler;
  exports["semigroupoidBuilder"] = semigroupoidBuilder;
  exports["categoryBuilder"] = categoryBuilder;
})(PS);
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["React.Basic.DOM.Events"] = $PS["React.Basic.DOM.Events"] || {};
  var exports = $PS["React.Basic.DOM.Events"];
  var Control_Category = $PS["Control.Category"];
  var Control_Semigroupoid = $PS["Control.Semigroupoid"];
  var Effect_Unsafe = $PS["Effect.Unsafe"];
  var React_Basic_Events = $PS["React.Basic.Events"];
  var stopPropagation = React_Basic_Events.unsafeEventFn(function (e) {
      return Effect_Unsafe.unsafePerformEffect(function __do() {
          var v = e.stopPropagation();
          return e;
      });
  });
  var preventDefault = React_Basic_Events.unsafeEventFn(function (e) {
      return Effect_Unsafe.unsafePerformEffect(function __do() {
          var v = e.preventDefault();
          return e;
      });
  });
  var capture = function (eventFn) {
      return React_Basic_Events.handler(Control_Semigroupoid.composeFlipped(React_Basic_Events.semigroupoidBuilder)(preventDefault)(Control_Semigroupoid.composeFlipped(React_Basic_Events.semigroupoidBuilder)(stopPropagation)(eventFn)));
  };
  var capture_ = function (cb) {
      return capture(Control_Category.identity(React_Basic_Events.categoryBuilder))(function (v) {
          return cb;
      });
  };
  exports["capture"] = capture;
  exports["capture_"] = capture_;
  exports["preventDefault"] = preventDefault;
  exports["stopPropagation"] = stopPropagation;
})(PS);
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["React.Basic.DOM.Internal"] = $PS["React.Basic.DOM.Internal"] || {};
  var exports = $PS["React.Basic.DOM.Internal"];
  var Unsafe_Coerce = $PS["Unsafe.Coerce"];                
  var unsafeCreateDOMComponent = Unsafe_Coerce.unsafeCoerce;
  exports["unsafeCreateDOMComponent"] = unsafeCreateDOMComponent;
})(PS);
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["React.Basic.DOM.Generated"] = $PS["React.Basic.DOM.Generated"] || {};
  var exports = $PS["React.Basic.DOM.Generated"];
  var React_Basic = $PS["React.Basic"];
  var React_Basic_DOM_Internal = $PS["React.Basic.DOM.Internal"];
  var p = function (dictUnion) {
      return React_Basic.element(React_Basic_DOM_Internal.unsafeCreateDOMComponent("p"));
  };
  var p_ = function (children) {
      return p()({
          children: children
      });
  };
  var h1 = function (dictUnion) {
      return React_Basic.element(React_Basic_DOM_Internal.unsafeCreateDOMComponent("h1"));
  };
  var h1_ = function (children) {
      return h1()({
          children: children
      });
  };
  var div = function (dictUnion) {
      return React_Basic.element(React_Basic_DOM_Internal.unsafeCreateDOMComponent("div"));
  };
  var div_ = function (children) {
      return div()({
          children: children
      });
  };
  var button = function (dictUnion) {
      return React_Basic.element(React_Basic_DOM_Internal.unsafeCreateDOMComponent("button"));
  };
  exports["button"] = button;
  exports["div"] = div;
  exports["div_"] = div_;
  exports["h1"] = h1;
  exports["h1_"] = h1_;
  exports["p"] = p;
  exports["p_"] = p_;
})(PS);
(function($PS) {
  "use strict";
  $PS["CounterClass"] = $PS["CounterClass"] || {};
  var exports = $PS["CounterClass"];
  var Data_Show = $PS["Data.Show"];
  var React_Basic = $PS["React.Basic"];
  var React_Basic_DOM = $PS["React.Basic.DOM"];
  var React_Basic_DOM_Events = $PS["React.Basic.DOM.Events"];
  var React_Basic_DOM_Generated = $PS["React.Basic.DOM.Generated"];                
  var component = React_Basic.createComponent("Counter");
  var counter = (function () {
      var render = function (self) {
          return React_Basic_DOM_Generated.div_([ React_Basic_DOM_Generated.h1_([ React_Basic_DOM.text("Counter (PS, class)") ]), React_Basic_DOM_Generated.p_([ React_Basic_DOM.text("You clicked " + (Data_Show.show(Data_Show.showInt)(self.state.counter) + " times")) ]), React_Basic_DOM_Generated.button()({
              onClick: React_Basic_DOM_Events.capture_(self.setState(function (s) {
                  return {
                      counter: s.counter + 1 | 0
                  };
              })),
              children: [ React_Basic_DOM.text("Click me") ]
          }) ]);
      };
      var initialState = {
          counter: 0
      };
      return React_Basic.make()(component)({
          initialState: initialState,
          render: render
      });
  })();
  exports["counter"] = counter;
})(PS);
module.exports = PS["CounterClass"];
